name: ParaCL CI
on: [push, pull_request]

jobs:
  debug_build:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ flex bison libfl-dev libgtest-dev ninja-build
    - name: configure
      run: |
        cmake -S . -B build/debug -DCMAKE_BUILD_TYPE=Debug -G Ninja
    - name: build
      run: |
        cmake --build build/debug --parallel `nproc`
    - name: test debug
      run: |
        cd build/debug 
        ctest --output-on-failure

  release_build:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ flex bison libfl-dev libgtest-dev ninja-build
    - name: configure
      run: |
        cmake -S . -B build/release -DCMAKE_BUILD_TYPE=Release -G Ninja
    - name: build
      run: |
        cmake --build build/release --parallel `nproc`
    - name: test release
      run: |
        cd build/release 
        ctest --output-on-failure
