name: ParaCL
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install G++
      run: sudo apt-get install -y cmake g++

    - name: CMake Build (Release)
      run: |
        cmake -S . -B build/release -DCMAKE_BUILD_TYPE=Release
        cmake --build build/release
        cd build/release

    - name: CMake Build (Debug)
      run: |
        cmake -S . -B build/debug -DCMAKE_BUILD_TYPE=Debug
        cmake --build build/debug
        cd build/debug