name: ParaCL
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: install deps
      run: |
          sudo apt-get install -y libgtest-dev cmake g++ flex bison libfl-dev

    - name: —Åheck versions of Flex and Bison 
      run: |
        flex --version
        bison --version
      
    - name: cmake release build  
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --parallel
        cd build
        ctest --output-on-failure

    - name: cmake debug build  
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
        cmake --build build --parallel
        cd build
        ctest --output-on-failure

    - name: ete tests
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
        cmake --build build --parallel
        cd tests/end-to-end
        chmod +x examples_runner.sh
        ./examples_runner.sh
